server:
  port: 8081
trello:
  key: 21ace8d2dbd8766edd36cef260d6ece9
  token: 1a7f9c7e44ad4e1aa9d9d670db30ee16e8b44b87c1cda9d653937cf3c2edde90
  url:
    get: https://api.trello.com/1/boards/5ebfd81910c42e0ee205bd01/cards
    post: https://api.trello.com/1/cards
rabbitmq:
  routingKey: trello-key
  queueName: trello-queue
  exchangeName: trello-exchange



# Connection via web-service
#spring:
#  rabbitmq:
#    addresses: amqp://gkfhmmyj:8875H8iutKHq4NJh4PHULqQGgJSOAmRF@rattlesnake.rmq.cloudamqp.com/gkfhmmyj
#    port: 5673

#spring.rabbitmq.host=rattlesnake.rmq.cloudamqp.com
#spring.rabbitmq.port=5672
#spring.rabbitmq.username=gkfhmmyj
#spring.rabbitmq.password=8875H8iutKHq4NJh4PHULqQGgJSOAmRF